"""
compress_html.py — PlatformIO pre-build script
Extracts HTML from web_ui.h / web_ui_dash.h / web_perf.h,
gzip-compresses at level 9, and writes include/web_ui_gz.h.

Runs automatically before every build via platformio.ini extra_scripts.
The generated file is intentionally excluded from version control (.gitignore).
"""
Import("env")  # noqa: F821  (PlatformIO injects this)

import gzip
import os
import re

HTML_SOURCES = [
    # (source_header,          var_name,     raw_literal_delimiter)
    ("include/web_ui.h",      "INDEX_HTML", "rawliteral"),
    ("include/web_ui_dash.h", "DASH_HTML",  "dash"),
    ("include/web_perf.h",    "PERF_HTML",  "rawliteral"),
    ("include/web_ui_car.h",  "CAR_HTML",   "rawliteral"),
]

OUTPUT_HEADER = "include/web_ui_gz.h"


def _read_firmware_version():
    """Read FIRMWARE_VERSION from include/version.h."""
    try:
        with open("include/version.h", "r", encoding="utf-8") as f:
            m = re.search(r'#define\s+FIRMWARE_VERSION\s+"([^"]+)"', f.read())
            if m:
                return m.group(1)
    except OSError:
        pass
    return "unknown"


def _compress(source, target, env):  # noqa: ARG001
    fw_version = _read_firmware_version()
    print(f"[compress_html] FIRMWARE_VERSION = {fw_version}")

    lines = [
        "// Auto-generated by compress_html.py — DO NOT EDIT",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
    ]

    for src_path, var_name, delimiter in HTML_SOURCES:
        if not os.path.exists(src_path):
            print(f"[compress_html] SKIP {src_path} (not found)")
            continue

        with open(src_path, "r", encoding="utf-8") as f:
            src_text = f.read()

        # Some headers use a C++ macro-injection trick to embed FIRMWARE_VERSION:
        #   R"delim(... html ...)delim" FIRMWARE_VERSION R"delim(... more ...)delim"
        # This splits the raw literal so the C++ compiler inserts the version string.
        # Substitute the macro before regex extraction so we capture the full HTML.
        src_text = src_text.replace(
            f')' + delimiter + '" FIRMWARE_VERSION R"' + delimiter + '(',
            fw_version
        )

        pattern = r'R"' + re.escape(delimiter) + r'\((.*?)\)' + re.escape(delimiter) + r'"'
        match = re.search(pattern, src_text, re.DOTALL)
        if not match:
            print(f"[compress_html] ERROR: could not parse {src_path}")
            continue

        html_bytes = match.group(1).encode("utf-8")
        gz_bytes   = gzip.compress(html_bytes, compresslevel=9)
        ratio      = (1.0 - len(gz_bytes) / len(html_bytes)) * 100.0

        print(f"[compress_html] {src_path}: {len(html_bytes):,} → {len(gz_bytes):,} bytes  ({ratio:.0f}% smaller)")

        hex_str = ", ".join(f"0x{b:02x}" for b in gz_bytes)
        lines.append(f"// {var_name}: {len(html_bytes):,} B → {len(gz_bytes):,} B (gzip -9)")
        lines.append(f"const uint8_t {var_name}_GZ[] PROGMEM = {{{hex_str}}};")
        lines.append(f"const size_t  {var_name}_GZ_LEN = {len(gz_bytes)};")
        lines.append("")

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[compress_html] Written {OUTPUT_HEADER}")


# Run immediately at script load so web_ui_gz.h is up-to-date BEFORE main.cpp compiles.
# (AddPreAction on the .elf only runs after .cpp.o files are built, which is too late
# when new HTML symbols were added — main.cpp would fail to compile referencing them.)
_compress(None, None, env)

# Also keep the pre-link hook so mid-session HTML edits get picked up.
env.AddPreAction("$BUILD_DIR/${PROGNAME}.elf", _compress)
