[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
build_flags =
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
monitor_speed = 115200
board_build.partitions = min_spiffs.csv

; Waveshare ESP32-S3-RS485-CAN (7-36V onboard power, integrated CAN transceiver)
; CAN TX = GPIO15, CAN RX = GPIO16
[env:esp32s3-waveshare]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
build_flags =
    -DTWAI_TX_PIN=15
    -DTWAI_RX_PIN=16
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
