/*
 * Tesla Open CAN Mod — ESP32 Web Edition
 * Core 0: WiFi AP + AsyncWebServer + OTA
 * Core 1: CAN bus read/modify/write (TWAI)
 *
 * GPLv3 — Based on tesla-open-can-mod
 */

#include <Arduino.h>
#include <WiFi.h>
#include <DNSServer.h>
#include <ESPmDNS.h>
#include <ESPAsyncWebServer.h>
#include <Update.h>
#include <Preferences.h>
#include <esp_task_wdt.h>
#include <driver/twai.h>
#include <esp_netif.h>
#include <SPIFFS.h>

#include "can_frame_types.h"
#include "drivers/twai_driver.h"
#include "handlers.h"
#include "version.h"
#include "web_ui_gz.h"   // auto-generated by compress_html.py (gzip of web_ui.h / web_ui_dash.h / web_perf.h)

// ── WiFi AP config (NVS-overridable) ──
static char apSSID[33] = "FSD-Controller";
static char apPass[64] = "12345678";

// ── WiFi STA config (connect to router) ──
static char staSSID[33] = "";
static char staPass[64] = "";
static bool staConnected = false;

// ── Globals ──
static DNSServer      dnsServer;
static TWAIDriver     canDriver;
static AsyncWebServer server(80);

static Preferences    prefs;
// Not static: mod_ota.h forward-declares this with `extern` so its background
// task can trigger a reboot after a successful pull-update.
volatile bool         otaPendingRestart = false;
static bool           safeModeActive    = false;

// Persist restart reason to NVS so it survives ANY reboot type (sw/panic/wdt/brownout).
// Read back in setup() → logged as "prev: <reason>". Cleared after read.
// Not static: forward-declared in mod_ota.h so pull-update path can call it.
void saveRestartReason(const char* tag) {
    Preferences diag;
    if (diag.begin("diag", false)) {
        diag.putString("rr", tag);
        diag.end();
    }
}

// ── Time sync (browser-pushed Unix timestamp) ──────────────────────
static volatile uint32_t timeUnixBase   = 0;   // Unix time at sync point
static volatile uint32_t timeMillisBase = 0;   // millis() at sync point
static volatile bool     timeSynced     = false;

// Returns Unix timestamp (when synced) or seconds-since-boot (fallback).
static inline uint32_t getUnixTime() {
    if (timeSynced) return timeUnixBase + (millis() - timeMillisBase) / 1000;
    return (millis() - cfg.uptimeStart) / 1000;
}

// ── Auth ──────────────────────────────────────────────────────────
static char sessionToken[17] = {0};  // 16 hex chars, reset on reboot
static char storedPin[17]    = {0};  // loaded from NVS; empty = no auth

static void generateToken() {
    uint32_t r1 = esp_random(), r2 = esp_random();
    snprintf(sessionToken, sizeof(sessionToken), "%08X%08X", r1, r2);
}

// Returns true if request is authorised.
// If no PIN is configured, always returns true (open access).
static bool checkToken(AsyncWebServerRequest* req) {
    if (storedPin[0] == '\0') return true;           // no PIN set → open
    if (sessionToken[0] == '\0') return false;        // PIN set but no token yet
    if (req->hasParam("token") &&
        req->getParam("token")->value().equals(sessionToken)) return true;
    return false;
}

// ── Log macros — stripped from release builds ──────────────────────
#ifdef DEBUG_MODE
#define DLOG(fmt, ...)  Serial.printf(fmt, ##__VA_ARGS__)
#define DLOGLN(msg)     Serial.println(msg)
#else
#define DLOG(fmt, ...)  do {} while (0)
#define DLOGLN(msg)     do {} while (0)
#endif

#ifndef PIN_LED
#define PIN_LED 2
#endif

// ── NVS key mapping (obfuscated) ───────────────────────────────────
// Config namespace "fsd":
#define NV_FSD_EN    "a1"
#define NV_HW_MODE   "a2"
#define NV_SP_PRO    "a3"
#define NV_PRO_AUTO  "a4"
#define NV_ISA_CHM   "a5"
#define NV_EM_DET    "a6"
#define NV_CN_MODE   "a7"
#define NV_AP_RST    "a9"
#define NV_PRECOND   "c2"
#define NV_AP_SSID   "c4"
#define NV_AP_PASS   "c5"
#define NV_STA_SSID  "c6"
#define NV_STA_PASS  "c7"
#define NV_OVR_SL    "c3"   // moved from "c5" (collided with NV_AP_PASS)
// Auth namespace "sec":
#define NV_PIN       "p1"
#define NV_HW4_OFF   "d1"
#define NV_TRACK_MD  "d2"
#define NV_HW3_AUTO  "d4"   // hw3AutoSpeed: enable auto speed targeting for low-speed limits

// ═══════════════════════════════════════════
//  Config persistence (NVS)
// ═══════════════════════════════════════════

// One-time migration from old verbose key names to obfuscated keys.
// Runs on first update; after migration old keys are removed.
static void migrateNvsKeys() {
    Preferences p;
    p.begin("fsd", false);
    if (!p.isKey(NV_FSD_EN) && p.isKey("fsdEn")) {
        p.putBool(NV_FSD_EN,   p.getBool("fsdEn",     false)); p.remove("fsdEn");
        p.putUChar(NV_HW_MODE, p.getUChar("hwMode",   2));     p.remove("hwMode");
        p.putUChar(NV_SP_PRO,  p.getUChar("spPro",    1));     p.remove("spPro");
        p.putBool(NV_PRO_AUTO, p.getBool("proAuto",   true));  p.remove("proAuto");
        p.putBool(NV_ISA_CHM,  p.getBool("isaChm",    false)); p.remove("isaChm");
        p.putBool(NV_EM_DET,   p.getBool("emDet",     true));  p.remove("emDet");
        p.putBool(NV_CN_MODE,  p.getBool("cnMode",    false)); p.remove("cnMode");
        p.putBool(NV_AP_RST,   p.getBool("apRestart", false)); p.remove("apRestart");
        // Legacy HW3 manual/smart/passthrough keys — feature removed in favor of
        // single hw3AutoSpeed toggle (see NV_HW3_AUTO). Drop any prior values.
        if (p.isKey("hw3Off"))   p.remove("hw3Off");
        if (p.isKey("hw3SmEn"))  p.remove("hw3SmEn");
        if (p.isKey("hw3SmT1"))  p.remove("hw3SmT1");
        if (p.isKey("hw3SmT2"))  p.remove("hw3SmT2");
        if (p.isKey("hw3SmT3"))  p.remove("hw3SmT3");
        if (p.isKey("hw3SmT4"))  p.remove("hw3SmT4");
        if (p.isKey("hw3SmO1"))  p.remove("hw3SmO1");
        if (p.isKey("hw3SmO2"))  p.remove("hw3SmO2");
        if (p.isKey("hw3SmO3"))  p.remove("hw3SmO3");
        if (p.isKey("hw3SmO4"))  p.remove("hw3SmO4");
        if (p.isKey("hw3SmO5"))  p.remove("hw3SmO5");
        if (p.isKey("precond")) p.remove("precond");  // feature removed
        if (p.isKey("apSSID")) { p.putString(NV_AP_SSID, p.getString("apSSID")); p.remove("apSSID"); }
        if (p.isKey("apPass")) { p.putString(NV_AP_PASS, p.getString("apPass")); p.remove("apPass"); }
        if (p.isKey("staSSID")){ p.putString(NV_STA_SSID,p.getString("staSSID"));p.remove("staSSID");}
        if (p.isKey("staPass")) { p.putString(NV_STA_PASS,p.getString("staPass"));p.remove("staPass");}
        DLOGLN("[NVS] migrated legacy keys");
    }
    // NV_OVR_SL moved "c5" → "c3" (c5 previously collided with NV_AP_PASS string
    // writes, producing garbage bool reads). We cannot reliably recover the user's
    // prior overrideSpeedLimit from "c5" because its contents may be string data.
    // On first boot after upgrade, default to safe=false and log.
    if (!p.isKey(NV_OVR_SL) && p.isKey(NV_FSD_EN)) {
        p.putBool(NV_OVR_SL, false);
        DLOGLN("[NVS] overrideSpeedLimit reset to false after c5→c3 migration");
    }
    // Remove retired obfuscated keys from the HW3 smart/manual/passthrough era.
    // These were all written by the previous firmware but the feature is gone.
    const char* retired[] = { "a8", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "c1", "d3" };
    for (auto* k : retired) if (p.isKey(k)) p.remove(k);
    p.end();
    // Migrate PIN
    Preferences sec;
    sec.begin("sec", false);
    if (!sec.isKey(NV_PIN) && sec.isKey("pin")) {
        sec.putString(NV_PIN, sec.getString("pin")); sec.remove("pin");
    }
    sec.end();
}

void loadConfig() {
    prefs.begin("fsd", false);
    cfg.fsdEnable          = prefs.getBool(NV_FSD_EN,   false);
    cfg.hwMode             = prefs.getUChar(NV_HW_MODE, 2);
    cfg.speedProfile       = prefs.getUChar(NV_SP_PRO,  1);
    cfg.profileModeAuto    = prefs.getBool(NV_PRO_AUTO, true);
    cfg.isaChimeSuppress   = prefs.getBool(NV_ISA_CHM,  false);
    cfg.emergencyDetection = prefs.getBool(NV_EM_DET,   true);
    cfg.forceActivate      = prefs.getBool(NV_CN_MODE,  false);
    cfg.overrideSpeedLimit = prefs.getBool(NV_OVR_SL,   false);
    cfg.apRestart          = prefs.getBool(NV_AP_RST,   false);
    // Legacy NVS key wipe: older firmware wrote a precondition bool here. Remove
    // so it stops consuming NVS space. Feature was removed (needs Vehicle CAN).
    if (prefs.isKey(NV_PRECOND)) prefs.remove(NV_PRECOND);
    cfg.hw4OffsetRaw       = prefs.getUChar(NV_HW4_OFF, 0);
    cfg.trackModeEnable    = prefs.getBool(NV_TRACK_MD, false);
    cfg.hw3AutoSpeed       = prefs.getBool(NV_HW3_AUTO, true);
    strlcpy(apSSID,  prefs.getString(NV_AP_SSID,  "FSD-Controller").c_str(), sizeof(apSSID));
    strlcpy(apPass,  prefs.getString(NV_AP_PASS,  "12345678").c_str(),       sizeof(apPass));
    strlcpy(staSSID, prefs.getString(NV_STA_SSID, "").c_str(),               sizeof(staSSID));
    strlcpy(staPass, prefs.getString(NV_STA_PASS, "").c_str(),               sizeof(staPass));

    prefs.end();

    // Load PIN from separate namespace
    Preferences secPrefs;
    secPrefs.begin("sec", false);
    strlcpy(storedPin, secPrefs.getString(NV_PIN, "").c_str(), sizeof(storedPin));
    secPrefs.end();

    // Clamp values
    if (cfg.hwMode > 2)       cfg.hwMode = 2;
    if (cfg.speedProfile > 4) cfg.speedProfile = 1;
}

void saveConfig() {
    prefs.begin("fsd", false);
    prefs.putBool(NV_FSD_EN,    cfg.fsdEnable);
    prefs.putUChar(NV_HW_MODE,  cfg.hwMode);
    prefs.putUChar(NV_SP_PRO,   cfg.speedProfile);
    prefs.putBool(NV_PRO_AUTO,  cfg.profileModeAuto);
    prefs.putBool(NV_ISA_CHM,   cfg.isaChimeSuppress);
    prefs.putBool(NV_EM_DET,    cfg.emergencyDetection);
    prefs.putBool(NV_CN_MODE,   cfg.forceActivate);
    prefs.putBool(NV_OVR_SL,    cfg.overrideSpeedLimit);
    prefs.putBool(NV_AP_RST,    cfg.apRestart);
    // NV_PRECOND no longer written — field is runtime-only until a UI surface returns.
    prefs.putUChar(NV_HW4_OFF,  cfg.hw4OffsetRaw);
    prefs.putBool(NV_TRACK_MD,  cfg.trackModeEnable);
    prefs.putBool(NV_HW3_AUTO,  cfg.hw3AutoSpeed);
    // WiFi keys written directly by /api/wifi — not touched here.
    prefs.end();
}

// ═══════════════════════════════════════════
//  SPIFFS persistent log  (Core 0 only)
// ═══════════════════════════════════════════
// File: /diag.log  max ~96 KB.
// When the file exceeds SPIFFS_LOG_MAX, the back half is kept (rotate in-place).
// All writes happen from Core 0 (loop / setupWebServer) — never from canTask.

static constexpr size_t SPIFFS_LOG_MAX   = 96 * 1024;  // 96 KB rotate threshold
static constexpr size_t SPIFFS_LOG_KEEP  = 48 * 1024;  // keep last 48 KB after rotate
static const char*      SPIFFS_LOG_PATH  = "/diag.log";
static bool             spiffsOK         = false;

// Rotate: keep only the last SPIFFS_LOG_KEEP bytes of the file.
static void spiffsRotate() {
    File f = SPIFFS.open(SPIFFS_LOG_PATH, "r");
    if (!f) return;
    size_t sz = f.size();
    if (sz <= SPIFFS_LOG_KEEP) { f.close(); return; }
    size_t skip = sz - SPIFFS_LOG_KEEP;
    f.seek(skip);
    // Read tail into a temporary buffer and rewrite the file.
    // We do this in 2 KB chunks to avoid a large stack allocation.
    static uint8_t rotBuf[2048];
    File tmp = SPIFFS.open("/diag.tmp", "w");
    if (!tmp) { f.close(); return; }
    while (f.available()) {
        size_t n = f.readBytes((char*)rotBuf, sizeof(rotBuf));
        if (n > 0) tmp.write(rotBuf, n);
    }
    f.close();
    tmp.close();
    SPIFFS.remove(SPIFFS_LOG_PATH);
    SPIFFS.rename("/diag.tmp", SPIFFS_LOG_PATH);
}

// Called once during setup — mount SPIFFS and write a BOOT marker.
static void setupSpiffs(const char* fwVersion) {
    if (!SPIFFS.begin(/*formatOnFail=*/true)) {
        DLOGLN("[SPIFFS] mount failed");
        return;
    }
    spiffsOK = true;
    File f = SPIFFS.open(SPIFFS_LOG_PATH, "a");
    if (f) {
        char marker[64];
        snprintf(marker, sizeof(marker), "\n=== BOOT v%s ===\n", fwVersion);
        f.print(marker);
        f.close();
    }
    DLOG("[SPIFFS] mounted  total=%u used=%u\n", (unsigned)SPIFFS.totalBytes(), (unsigned)SPIFFS.usedBytes());
}

// Called from loop() every 3 s — appends any new RAM ring-buffer entries to flash.
static void flushLogsToSpiffs() {
    if (!spiffsOK) return;
    uint32_t total = diagTotal;  // snapshot (volatile read)
    if (total == diagFlushed) return;  // nothing new

    File f = SPIFFS.open(SPIFFS_LOG_PATH, "a");
    if (!f) return;

    // Walk the ring buffer from diagFlushed to total.
    // diagBuf holds at most DIAG_CAP entries; if more than DIAG_CAP have been written
    // since last flush we can only recover the most recent DIAG_CAP.
    uint32_t pending = total - diagFlushed;
    uint32_t skip    = (pending > DIAG_CAP) ? pending - DIAG_CAP : 0;
    uint32_t start   = diagFlushed + skip;

    for (uint32_t t = start; t < total; t++) {
        // Map monotonic index t → ring buffer slot.
        // diagHead points to the *next* write slot, so the oldest entry in the
        // ring is at (diagHead + DIAG_CAP - diagCount) % DIAG_CAP when full.
        // Simpler: entry at absolute index t is at slot t % DIAG_CAP.
        uint16_t slot = (uint16_t)(t % DIAG_CAP);
        f.print(diagBuf[slot]);
        f.print('\n');
    }
    f.close();
    diagFlushed = total;

    // Rotate if the file has grown too large.
    File fr = SPIFFS.open(SPIFFS_LOG_PATH, "r");
    if (fr) {
        size_t sz = fr.size();
        fr.close();
        if (sz >= SPIFFS_LOG_MAX) spiffsRotate();
    }
}

// ═══════════════════════════════════════════
//  Web Server Setup (runs on Core 0)
// ═══════════════════════════════════════════

void setupWebServer() {
    // ── Captive portal — iOS & Android auto-detection ─────────────────
    // iOS tries /hotspot-detect.html; redirect to main page.
    server.on("/hotspot-detect.html", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->redirect("http://" + WiFi.softAPIP().toString() + "/");
    });
    // iOS 14+
    server.on("/library/test/success.html", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->send(200, "text/html", "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>");
    });
    // Android generate_204
    server.on("/generate_204", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->redirect("http://" + WiFi.softAPIP().toString() + "/");
    });
    // Windows NCSI
    server.on("/connecttest.txt", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->send(200, "text/plain", "Microsoft NCSI");
    });
    server.on("/ncsi.txt", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->send(200, "text/plain", "Microsoft NCSI");
    });

    // Serve UI — use beginResponse_P (AsyncProgmemResponse) to stream from flash
    // in chunks; avoids the 60 KB contiguous heap allocation that AsyncBasicResponse
    // would need, which fails after WiFi starts and causes a memmove(NULL) crash.
    server.on("/", HTTP_GET, [](AsyncWebServerRequest* req) {
        // Tesla 车机 UA 自动重定向到 /car（除非 ?ui=phone 强制）
        // - Intel MCU: UA 含 "Tesla" / "QtCarBrowser"
        // - AMD MCU (Chromium): UA 形如 "X11; Linux x86_64 ... Chrome"，无 Tesla 标识
        //   → 用 "Linux" 且 不含 "Android" 命中（排除安卓手机）。Linux 桌面会误中，
        //     用户可点 /car 悬浮"手机版"按钮 (openPhone → /?ui=phone) 返回。
        bool forcePhone = req->hasParam("ui") && req->getParam("ui")->value() == "phone";
        if (!forcePhone && req->hasHeader("User-Agent")) {
            String ua = req->header("User-Agent");
            bool isCar = ua.indexOf("Tesla") >= 0 || ua.indexOf("QtCarBrowser") >= 0;
            if (!isCar && ua.indexOf("Linux") >= 0 && ua.indexOf("Android") < 0) {
                isCar = true;
            }
            if (isCar) {
                req->redirect("/car");
                return;
            }
        }
        auto* r = req->beginResponse(200, "text/html", INDEX_HTML_GZ, INDEX_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        req->send(r);
    });

    // 车机横屏 UI — 大字号大按钮，复用所有 /api/* 端点
    server.on("/car", HTTP_GET, [](AsyncWebServerRequest* req) {
        auto* r = req->beginResponse(200, "text/html", CAR_HTML_GZ, CAR_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        req->send(r);
    });

    // Dashboard page — instrument cluster view (token checked via JS)
    server.on("/dash", HTTP_GET, [](AsyncWebServerRequest* req) {
        auto* r = req->beginResponse(200, "text/html", DASH_HTML_GZ, DASH_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        req->send(r);
    });

    // Performance test page
    server.on("/perf", HTTP_GET, [](AsyncWebServerRequest* req) {
        auto* r = req->beginResponse(200, "text/html", PERF_HTML_GZ, PERF_HTML_GZ_LEN);
        r->addHeader("Content-Encoding", "gzip");
        r->addHeader("Cache-Control", "no-store, no-cache, must-revalidate");
        req->send(r);
    });

    server.on("/manifest.json", HTTP_GET, [](AsyncWebServerRequest* req) {
        req->send(200, "application/manifest+json",
            "{\"name\":\"\xE7\x89\xB9\xE6\x96\xAF\xE6\x8B\x89\xE6\x8E\xA7\xE5\x88\xB6\xE5\x99\xA8\",\"short_name\":\"\xE6\x8E\xA7\xE5\x88\xB6\xE5\x99\xA8\","
            "\"display\":\"fullscreen\",\"orientation\":\"landscape\","
            "\"background_color\":\"#05080f\",\"theme_color\":\"#05080f\","
            "\"start_url\":\"/dash\",\"scope\":\"/\","
            "\"icons\":[]}");
    });

    // Performance test control API
    server.on("/api/perf", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "Forbidden"); return; }
        if (req->hasParam("cmd")) {
            String cmd = req->getParam("cmd")->value();
            if (cmd == "arm_accel")   { cfg.perfAccelState = 1; cfg.perfAccelMs = 0; }
            else if (cmd == "arm_brake")  { cfg.perfBrakeState = 1; cfg.perfBrakeMs = 0; }
            else if (cmd == "reset_accel"){ cfg.perfAccelState = 0; cfg.perfAccelMs = 0; }
            else if (cmd == "reset_brake"){ cfg.perfBrakeState = 0; cfg.perfBrakeMs = 0; }
            else if (cmd == "reset")  { cfg.perfAccelState = 0; cfg.perfAccelMs = 0;
                                        cfg.perfBrakeState = 0; cfg.perfBrakeMs = 0; }
        }
        req->send(200, "application/json", "{\"ok\":true}");
    });

    // Status JSON — use %u for uint32_t on ESP32
    server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest* req) {
        uint32_t uptime = (millis() - cfg.uptimeStart) / 1000;

        // JSON-escape apSSID (guard against " and \ in SSID)
        char escapedSSID[128] = {};
        const char* src = apSSID;
        char* dst = escapedSSID;
        char* end = escapedSSID + sizeof(escapedSSID) - 3;
        while (*src && dst < end) {
            if (*src == '"' || *src == '\\') *dst++ = '\\';
            *dst++ = *src++;
        }

        char buf[2400];
        static_assert(sizeof(buf) >= 2400, "JSON buffer too small");
        snprintf(buf, sizeof(buf),
            "{\"rx\":%u,\"modified\":%u,\"errors\":%u,\"uptime\":%u,"
            "\"canOK\":%s,\"fsdTriggered\":%s,"
            "\"fsdEnable\":%d,\"hwMode\":%d,\"speedProfile\":%d,\"gwAutopilot\":%d,"
            "\"profileMode\":%d,\"isaChime\":%d,\"emergencyDet\":%d,\"forceActivate\":%d,\"overrideSL\":%d,"
            "\"hw3AutoOffset\":%d,\"hwDetected\":%d,"
            "\"hw3AutoSpeed\":%d,\"fusedLimit\":%u,"
            "\"tempSeen\":%s,\"tempInRaw\":%u,\"tempOutRaw\":%u,"
            "\"bmsSeen\":%s,\"bmsV\":%u,\"bmsA\":%d,\"bmsSoc\":%u,"
            "\"bmsMinT\":%d,\"bmsMaxT\":%d,"
            "\"freeHeap\":%u,\"safeMode\":%s,\"pinRequired\":%s,"
            "\"timeSynced\":%s,"
            "\"speedD\":%u,\"gearRaw\":%u,\"torqueF\":%d,\"torqueR\":%d,"
            "\"adaptLighting\":%s,\"hbForce\":%s,"
            "\"visionLimit\":%u,\"nagLevel\":%u,\"fcw\":%u,\"accState\":%u,\"brake\":%s,"
            "\"sideCol\":%u,\"laneWarn\":%u,\"laneChg\":%u,"
            "\"autosteer\":%s,\"aeb\":%s,\"fcwOn\":%s,"
            "\"apRestart\":%s,\"hw4Offset\":%u,\"trackMode\":%d,"
            "\"perfAccel\":%u,\"perfBrake\":%u,\"perfAccelMs\":%u,\"perfBrakeMs\":%u,\"brakeEntryKph\":%u,"
            "\"apSSID\":\"%s\",\"staSSID\":\"%s\",\"staIP\":\"%s\",\"staOK\":%s,"
            "\"variant\":\"%s\",\"version\":\"%s\"}",
            (unsigned)cfg.rxCount, (unsigned)cfg.modifiedCount,
            (unsigned)cfg.errorCount, (unsigned)uptime,
            cfg.canOK ? "true" : "false",
            cfg.fsdTriggered ? "true" : "false",
            (int)cfg.fsdEnable,
            (int)cfg.hwMode,
            (int)cfg.speedProfile,
            (int)cfg.gatewayAutopilot,
            (int)cfg.profileModeAuto,
            (int)cfg.isaChimeSuppress,
            (int)cfg.emergencyDetection,
            (int)cfg.forceActivate,
            (int)cfg.overrideSpeedLimit,
            (int)cfg.hw3SpeedOffset,
            (int)cfg.hwDetected,
            (int)cfg.hw3AutoSpeed,
            (unsigned)cfg.fusedSpeedLimit,
            cfg.tempSeen ? "true" : "false",
            (unsigned)cfg.tempInsideRaw,    // × 0.25 = °C  (done in JS)
            (unsigned)cfg.tempOutsideRaw,   // × 0.5 − 40 = °C  (done in JS)
            cfg.bmsSeen ? "true" : "false",
            (unsigned)cfg.packVoltage_cV,   // ÷100 = V  (done in JS)
            (int)cfg.packCurrent_dA,        // ÷10  = A  (done in JS)
            (unsigned)cfg.socPercent_d,     // ÷10  = %  (done in JS)
            (int)cfg.battTempMin,
            (int)cfg.battTempMax,
            (unsigned)esp_get_free_heap_size(),
            safeModeActive ? "true" : "false",
            (storedPin[0] != '\0') ? "true" : "false",
            timeSynced ? "true" : "false",
            (unsigned)telemSpeedRaw(), (unsigned)telemGear(),
            (int)telemTorqueFront(), (int)telemTorqueRear(),
            cfg.adaptiveLighting ? "true" : "false",
            cfg.highBeamForce    ? "true" : "false",
            (unsigned)cfg.visionSpeedLimit,
            (unsigned)cfg.nagLevel,
            (unsigned)cfg.fcwLevel,
            (unsigned)cfg.accState,
            telemBrake() ? "true" : "false",
            (unsigned)cfg.sideCollision,
            (unsigned)cfg.laneDeptWarning,
            (unsigned)cfg.laneChangeState,
            cfg.autosteerOn ? "true" : "false",
            cfg.aebOn       ? "true" : "false",
            cfg.fcwOn       ? "true" : "false",
            cfg.apRestart   ? "true" : "false",
            (unsigned)cfg.hw4OffsetRaw,
            (int)cfg.trackModeEnable,
            (unsigned)cfg.perfAccelState, (unsigned)cfg.perfBrakeState,
            (unsigned)cfg.perfAccelMs,    (unsigned)cfg.perfBrakeMs,
            (unsigned)cfg.perfBrakeEntryKph,
            escapedSSID,
            staSSID,
            (WiFi.status() == WL_CONNECTED) ? WiFi.localIP().toString().c_str() : "",
            (WiFi.status() == WL_CONNECTED) ? "true" : "false",
            FIRMWARE_VARIANT,
            FIRMWARE_VERSION
        );

#ifdef DEBUG_MODE
        if (cfg.dbgFrameCaptured) {
            char dbg[120];
            snprintf(dbg, sizeof(dbg),
                ",\"dbg\":{\"captured\":true,\"bytes\":\"%02X %02X %02X %02X %02X %02X %02X %02X\",\"bit30\":%d}",
                cfg.dbgFrame[0], cfg.dbgFrame[1], cfg.dbgFrame[2], cfg.dbgFrame[3],
                cfg.dbgFrame[4], cfg.dbgFrame[5], cfg.dbgFrame[6], cfg.dbgFrame[7],
                (cfg.dbgFrame[3] >> 6) & 0x01
            );
            size_t len = strlen(buf);
            buf[len - 1] = '\0';
            strlcat(buf, dbg, sizeof(buf));
            strlcat(buf, "}", sizeof(buf));
        }
#endif
        req->send(200, "application/json", buf);
    });

    // Auth — validate PIN, return session token
    server.on("/api/auth", HTTP_POST, [](AsyncWebServerRequest* req) {
        String pin = req->hasParam("pin", true) ? req->getParam("pin", true)->value() : "";
        if (strcmp(pin.c_str(), storedPin) == 0) {
            generateToken();
            req->send(200, "text/plain", sessionToken);
        } else {
            req->send(403, "text/plain", "WRONG");
        }
    });

    // Change PIN (requires current token)
    server.on("/api/pin", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        String newPin = req->hasParam("pin", true) ? req->getParam("pin", true)->value() : "";
        if (newPin.length() > 16) { req->send(400, "text/plain", "TOO_LONG"); return; }
        if (newPin.length() > 0 && newPin.length() < 4) { req->send(400, "text/plain", "TOO_SHORT"); return; }
        strlcpy(storedPin, newPin.c_str(), sizeof(storedPin));
        Preferences secPrefs;
        secPrefs.begin("sec", false);
        secPrefs.putString(NV_PIN, newPin);
        secPrefs.end();
        sessionToken[0] = '\0';  // invalidate existing tokens
        req->send(200, "text/plain", "OK");
    });

    // Set config — with input validation and NVS write-only-on-change
    server.on("/api/set", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }

        // ── Validate ALL numeric params up-front; mutate only after every check passes.
        // Otherwise a later invalid param would leave cfg half-updated on 400.
        if (req->hasParam("hwMode")) {
            int raw = req->getParam("hwMode")->value().toInt();
            if (raw < 0 || raw > 2) { req->send(400, "text/plain", "bad hwMode"); return; }
        }
        if (req->hasParam("speedProfile")) {
            int raw = req->getParam("speedProfile")->value().toInt();
            if (raw < 0 || raw > 4) { req->send(400, "text/plain", "bad speedProfile"); return; }
            // Only HW4 (hwMode=2) supports extended profiles 3..4; HW3 and Legacy cap at 0..2.
            uint8_t curHw = req->hasParam("hwMode") ? (uint8_t)req->getParam("hwMode")->value().toInt() : cfg.hwMode;
            if (curHw != 2 && raw > 2) { req->send(400, "text/plain", "speedProfile out of range for non-HW4"); return; }
        }
        if (req->hasParam("hw4Offset")) {
            int raw = req->getParam("hw4Offset")->value().toInt();
            if (raw != 0 && raw != 7 && raw != 10 && raw != 14 && raw != 21) {
                req->send(400, "text/plain", "bad hw4Offset"); return;
            }
        }

        bool changed = false;

        if (req->hasParam("fsdEnable")) {
            bool v = req->getParam("fsdEnable")->value().toInt() != 0;
            if (v != cfg.fsdEnable) { cfg.fsdEnable = v; changed = true; }
        }
        if (req->hasParam("hwMode")) {
            uint8_t v = (uint8_t)req->getParam("hwMode")->value().toInt();
            if (v != cfg.hwMode) { cfg.hwMode = v; changed = true; }
        }
        if (req->hasParam("speedProfile")) {
            uint8_t v = (uint8_t)req->getParam("speedProfile")->value().toInt();
            if (v != cfg.speedProfile) { cfg.speedProfile = v; changed = true; }
        }
        // If hwMode just transitioned away from HW4 and no fresh speedProfile was
        // supplied, clamp any stale HW4-only value (3/4) to 2 — otherwise HW3/Legacy
        // would silently operate on an out-of-range profile.
        if (cfg.hwMode != 2 && cfg.speedProfile > 2) {
            cfg.speedProfile = 2;
            changed = true;
        }
        if (req->hasParam("profileMode")) {
            bool v = req->getParam("profileMode")->value().toInt() != 0;
            if (v != cfg.profileModeAuto) { cfg.profileModeAuto = v; changed = true; }
        }
        if (req->hasParam("isaChime")) {
            bool v = req->getParam("isaChime")->value().toInt() != 0;
            if (v != cfg.isaChimeSuppress) { cfg.isaChimeSuppress = v; changed = true; }
        }
        if (req->hasParam("emergencyDet")) {
            bool v = req->getParam("emergencyDet")->value().toInt() != 0;
            if (v != cfg.emergencyDetection) { cfg.emergencyDetection = v; changed = true; }
        }
        if (req->hasParam("forceActivate")) {
            bool v = req->getParam("forceActivate")->value().toInt() != 0;
            if (v != cfg.forceActivate) { cfg.forceActivate = v; changed = true; }
        }
        if (req->hasParam("overrideSL")) {
            bool v = req->getParam("overrideSL")->value().toInt() != 0;
            if (v != cfg.overrideSpeedLimit) { cfg.overrideSpeedLimit = v; changed = true; }
        }
        if (req->hasParam("hw3AutoSpeed")) {
            bool v = req->getParam("hw3AutoSpeed")->value().toInt() != 0;
            if (v != cfg.hw3AutoSpeed) { cfg.hw3AutoSpeed = v; changed = true; }
        }
        // precond removed from UI — requires Vehicle CAN (X179 pin 9/10)
        if (req->hasParam("hw4Offset")) {
            uint8_t v = (uint8_t)req->getParam("hw4Offset")->value().toInt();
            if (v != cfg.hw4OffsetRaw) { cfg.hw4OffsetRaw = v; changed = true; }
        }
        if (req->hasParam("trackMode")) {
            bool v = req->getParam("trackMode")->value().toInt() != 0;
            if (v != cfg.trackModeEnable) { cfg.trackModeEnable = v; changed = true; }
        }

        if (changed) saveConfig();
        req->send(200, "text/plain", "OK");
    });

    // WiFi AP settings — save to NVS then restart
    server.on("/api/wifi", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        if (!req->hasParam("ssid", true)) {
            req->send(400, "text/plain", "Missing ssid");
            return;
        }
        String newSSID = req->getParam("ssid", true)->value();
        String newPass = req->hasParam("pass", true) ? req->getParam("pass", true)->value() : "";
        newSSID.trim();
        if (newSSID.length() == 0 || newSSID.length() > 32) {
            req->send(400, "text/plain", "SSID must be 1-32 chars");
            return;
        }
        if (newPass.length() > 0 && newPass.length() < 8) {
            req->send(400, "text/plain", "Password must be >= 8 chars");
            return;
        }
        Preferences wPrefs;
        wPrefs.begin("fsd", false);
        wPrefs.putString(NV_AP_SSID, newSSID);
        if (newPass.length() >= 8) wPrefs.putString(NV_AP_PASS, newPass);
        wPrefs.end();
        req->send(200, "text/plain", "OK");
        saveRestartReason("/api/ap save");
        otaPendingRestart = true;
    });

    // WiFi scan — two-endpoint non-blocking design:
    //   GET /api/scan        → kick off async scan, return immediately
    //   GET /api/scan/result → poll for completion; returns {"scanning":true} while
    //                          in progress, or the SSID array when done.
    // This keeps the async_service_task free during the ~1-2 s channel sweep.
    // exact() required — default matcher would let /api/scan swallow /api/scan/result.
    server.on(AsyncURIMatcher::exact("/api/scan"), HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        WiFi.scanDelete();
        WiFi.scanNetworks(/*async=*/true, /*hidden=*/false,
                          /*passive=*/false, /*max_ms_per_chan=*/300,
                          /*channel=*/0);
        req->send(200, "application/json", "{\"scanning\":true}");
    });

    server.on("/api/scan/result", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        int n = WiFi.scanComplete();
        if (n == WIFI_SCAN_RUNNING) {
            req->send(200, "application/json", "{\"scanning\":true}");
            return;
        }
        uint32_t up = (millis() - cfg.uptimeStart) / 1000;
        if (n <= 0) {
            char logMsg[48];
            snprintf(logMsg, sizeof(logMsg), "WiFi scan: %d networks (err=%d)", n, n);
            addDiagLog(up, logMsg);
            WiFi.scanDelete();
            req->send(200, "application/json", "[]");
            return;
        }
        char logMsg[48];
        snprintf(logMsg, sizeof(logMsg), "WiFi scan: %d networks found", n);
        addDiagLog(up, logMsg);
        String json = "[";
        for (int i = 0; i < n; i++) {
            if (i > 0) json += ",";
            String ssid = WiFi.SSID(i);
            ssid.replace("\\", "\\\\");
            ssid.replace("\"", "\\\"");
            json += "{\"ssid\":\"" + ssid + "\",\"rssi\":" + String(WiFi.RSSI(i)) + "}";
        }
        json += "]";
        WiFi.scanDelete();
        req->send(200, "application/json", json);
    });

    // WiFi STA settings — connect module to router
    server.on("/api/sta", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        String newSSID = req->hasParam("ssid", true) ? req->getParam("ssid", true)->value() : "";
        String newPass = req->hasParam("pass", true) ? req->getParam("pass", true)->value() : "";
        newSSID.trim();
        if (newSSID.length() == 0) {
            Preferences wPrefs;
            wPrefs.begin("fsd", false);
            wPrefs.putString(NV_STA_SSID, "");
            wPrefs.putString(NV_STA_PASS, "");
            wPrefs.end();
            req->send(200, "text/plain", "OK");
            saveRestartReason("/api/sta clear");
            otaPendingRestart = true;
            return;
        }
        if (newSSID.length() > 32) { req->send(400, "text/plain", "SSID too long"); return; }
        // WPA2 requires 8-63 chars; empty allowed for open networks
        if (newPass.length() > 0 && (newPass.length() < 8 || newPass.length() > 63)) {
            req->send(400, "text/plain", "Password must be 8-63 chars"); return;
        }
        Preferences wPrefs;
        wPrefs.begin("fsd", false);
        wPrefs.putString(NV_STA_SSID, newSSID);
        wPrefs.putString(NV_STA_PASS, newPass);
        wPrefs.end();
        req->send(200, "text/plain", "OK");
        saveRestartReason("/api/sta save");
        otaPendingRestart = true;
    });

    // Time sync — browser pushes its Unix timestamp so CSV rows carry real time
    server.on("/api/time", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        if (!req->hasParam("ts", true)) { req->send(400, "text/plain", "Missing ts"); return; }
        uint32_t ts = (uint32_t)req->getParam("ts", true)->value().toInt();
        if (ts < 1700000000UL) { req->send(400, "text/plain", "Invalid"); return; }
        timeUnixBase   = ts;
        timeMillisBase = millis();
        timeSynced     = true;
        req->send(200, "text/plain", "OK");
    });

    // Diagnostic log — stream all entries as plain text (GET) or clear (POST /api/log/clear).
    // exact() required — default matcher would hijack /api/log/download (same HTTP method).
    server.on(AsyncURIMatcher::exact("/api/log"), HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        AsyncResponseStream* resp = req->beginResponseStream("text/plain; charset=utf-8");
        uint16_t cnt = diagLogCount();
        if (cnt == 0) {
            resp->print("(no log entries)\n");
        } else {
            for (uint16_t i = 0; i < cnt; i++) {
                resp->print(diagLogAt(i));
                resp->print('\n');
            }
        }
        req->send(resp);
    });

    server.on("/api/log/clear", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        diagLogClear();
        if (spiffsOK) SPIFFS.remove(SPIFFS_LOG_PATH);
        req->send(200, "text/plain", "OK");
    });

    // Download full persistent log from SPIFFS as a text attachment.
    server.on("/api/log/download", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        if (!spiffsOK || !SPIFFS.exists(SPIFFS_LOG_PATH)) {
            req->send(404, "text/plain", "No persistent log");
            return;
        }
        AsyncWebServerResponse* resp = req->beginResponse(
            SPIFFS, SPIFFS_LOG_PATH, "text/plain");
        resp->addHeader("Content-Disposition",
                        "attachment; filename=\"diag.log\"");
        req->send(resp);
    });

    // /api/highbeam removed — requires Vehicle CAN (X179 pin 9/10), not available on Party CAN

    // AP auto-restart toggle
    server.on("/api/aprestart", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        if (!req->hasParam("en")) { req->send(400, "text/plain", "Missing en"); return; }
        cfg.apRestart = req->getParam("en")->value().toInt() != 0;
        saveConfig();
        req->send(200, "application/json", "{\"ok\":true}");
    });

    // Manual reboot — flag-based (same pattern as OTA restart)
    server.on("/api/reboot", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        req->send(200, "application/json", "{\"ok\":true}");
        saveRestartReason("/api/reboot");
        otaPendingRestart = true;
    });

    server.on("/api/reset", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        // Clear all namespaces
        prefs.begin("fsd", false);
        prefs.clear();
        prefs.end();
        Preferences secPrefs;
        secPrefs.begin("sec", false);
        secPrefs.clear();
        secPrefs.end();
        Preferences sysPrefs;
        sysPrefs.begin("sys", false);
        sysPrefs.clear();
        sysPrefs.end();
        // Reload defaults into cfg and restart
        req->send(200, "application/json", "{\"ok\":true}");
        saveRestartReason("/api/reset");
        otaPendingRestart = true;
    });

    // OTA firmware upload — flag-based restart (no delay in async context).
    // MUST use exact() matcher — otherwise ESPAsyncWebServer's default
    // BackwardCompatible matching also catches /api/ota/check, /api/ota/pull
    // etc., hijacks them, and reboots the device because Update.hasError()
    // returns false when Update was never started.
    server.on(AsyncURIMatcher::exact("/api/ota"), HTTP_POST,
        [](AsyncWebServerRequest* req) {
            if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
            bool ok = !Update.hasError();
            req->send(200, "text/plain", ok ? "OK" : "FAIL");
            if (ok) {
                saveRestartReason("/api/ota upload");
                otaPendingRestart = true;
            }
        },
        [](AsyncWebServerRequest* req, const String& filename,
           size_t index, uint8_t* data, size_t len, bool final) {
            if (!checkToken(req)) return;  // block unauthorized uploads
            if (index == 0) {
                DLOG("OTA start: %s\n", filename.c_str());
                if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
#ifdef DEBUG_MODE
                    Update.printError(Serial);
#endif
                }
            }
            if (Update.isRunning()) {
                if (Update.write(data, len) != len) {
#ifdef DEBUG_MODE
                    Update.printError(Serial);
#endif
                }
            }
            if (final) {
                if (Update.end(true)) {
                    DLOG("OTA done: %u bytes\n", (unsigned)(index + len));
                } else {
#ifdef DEBUG_MODE
                    Update.printError(Serial);
#endif
                }
            }
        }
    );

    // ── Online OTA (pull from GitHub Releases) ──
    server.on("/api/ota/check", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        if (!otaStartCheck()) { req->send(409, "text/plain", "BUSY"); return; }
        req->send(200, "application/json", "{\"ok\":true}");
    });

    server.on("/api/ota/pull", HTTP_POST, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        String url = req->hasParam("url", true) ? req->getParam("url", true)->value()
                   : String(otaLatestUrl());
        if (url.length() == 0 || !url.startsWith("https://")) {
            req->send(400, "text/plain", "BAD_URL");
            return;
        }
        if (!otaStartPull(url.c_str())) { req->send(409, "text/plain", "BUSY"); return; }
        req->send(200, "application/json", "{\"ok\":true}");
    });

    server.on("/api/ota/status", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(403, "text/plain", "UNAUTH"); return; }
        char buf[640];
        otaStatusJson(buf, sizeof(buf));
        req->send(200, "application/json", buf);
    });

#ifdef WIFI_BRIDGE_ENABLED
    // ── WiFi bridge + DNS filter API ──────────────────────────────────────────
    server.on("/api/wifi-bridge/status", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(401, "text/plain", "unauthorized"); return; }
        bool upConnected = WiFi.status() == WL_CONNECTED;
        int32_t upRSSI = upConnected ? WiFi.RSSI() : 0;
        String upIP = upConnected ? WiFi.localIP().toString() : String();

        uint32_t totalBlocked = 0;
        DNSBlockedDomainStatEntry entries[kDnsBlockedDomainCapacity];
        size_t recentBlocked = gDnsFilter.copyBlockedDomains(entries, kDnsBlockedDomainCapacity, totalBlocked);

        String json;
        json.reserve(3200);
        json += "{";
        json += "\"upstreamEnable\":"; json += (gWifiBridgeCfg.enabled ? "true" : "false");
        json += ",\"upstreamConnected\":"; json += (upConnected ? "true" : "false");
        json += ",\"upstreamRSSI\":"; json += (upConnected ? String(upRSSI) : String("null"));
        json += ",\"upstreamSSID\":\""; json += wifiBridgeJsonEscape(wifiBridgeActiveSSID()); json += "\"";
        json += ",\"upstreamIP\":\""; json += wifiBridgeJsonEscape(upIP); json += "\"";
        json += ",\"upstreamStatus\":\""; json += wifiBridgeJsonEscape(String(wifiBridgeUpstreamStatusText())); json += "\"";
        json += ",\"upstreamSignal\":\""; json += (upConnected ? wifiBridgeJsonEscape(String(wifiBridgeSignalText(upRSSI))) : String()); json += "\"";
        // Snapshot networks under mux (HTTP task vs loop task writers). Copy to
        // locals so JSON-building String ops run outside the critical section.
        SavedUpstreamNetwork snap[MAX_UPSTREAM_NETWORKS];
        uint8_t snapCount = 0;
        portENTER_CRITICAL(&gWifiBridgeMux);
        snapCount = gWifiBridgeCfg.networkCount;
        for (uint8_t i = 0; i < snapCount && i < MAX_UPSTREAM_NETWORKS; ++i) {
            snap[i] = gWifiBridgeCfg.networks[i];
        }
        portEXIT_CRITICAL(&gWifiBridgeMux);

        json += ",\"upstreamSavedCount\":"; json += String((unsigned)snapCount);
        json += ",\"upstreamNetworks\":[";
        String connectedSSID = wifiBridgeConnectedSSID();
        String activeSSID = wifiBridgeActiveSSID();
        for (uint8_t i = 0; i < snapCount; ++i) {
            if (i > 0) json += ",";
            json += "{\"ssid\":\""; json += wifiBridgeJsonEscape(String(snap[i].ssid));
            json += "\",\"hasPass\":"; json += (snap[i].pass[0] != '\0' ? "true" : "false");
            json += ",\"connected\":"; json += (connectedSSID.equals(snap[i].ssid) ? "true" : "false");
            json += ",\"active\":"; json += (activeSSID.equals(snap[i].ssid) ? "true" : "false");
            json += "}";
        }
        json += "]";
        json += ",\"natEnabled\":"; json += (gNatEnabled ? "true" : "false");
        json += ",\"natStatus\":\""; json += wifiBridgeJsonEscape(String(wifiBridgeNatStatusText())); json += "\"";
        json += ",\"chipTempC\":"; json += (std::isfinite(gThermalStatus.currentC) ? String(gThermalStatus.currentC, 1) : String("null"));
        json += ",\"chipTempAvgC\":"; json += (std::isfinite(gThermalStatus.averageC) ? String(gThermalStatus.averageC, 1) : String("null"));
        json += ",\"thermalStatus\":\""; json += wifiBridgeJsonEscape(String(thermalStatusText())); json += "\"";
        json += ",\"thermalProtect\":"; json += (thermalProtectActive() ? "true" : "false");
        json += ",\"dnsEnable\":"; json += (gDnsFilterCfg.enabled ? "true" : "false");
        json += ",\"dnsAllowCount\":"; json += String((unsigned)wifiBridgeDnsRuleCount(gDnsFilterCfg.allowlist));
        json += ",\"dnsBlockCount\":"; json += String((unsigned)wifiBridgeDnsRuleCount(gDnsFilterCfg.blocklist));
        json += ",\"dnsAllow\":\""; json += wifiBridgeJsonEscape(String(gDnsFilterCfg.allowlist)); json += "\"";
        json += ",\"dnsBlock\":\""; json += wifiBridgeJsonEscape(String(gDnsFilterCfg.blocklist)); json += "\"";
        json += ",\"dnsBlockedTotal\":"; json += String((unsigned)totalBlocked);
        uint32_t ipDrops = 0, ipCache = 0, ipPeak = 0;
        dnsIpBlockerGetStats(&ipDrops, &ipCache, &ipPeak);
        json += ",\"ipBlockDrops\":"; json += String((unsigned)ipDrops);
        json += ",\"ipCacheCount\":"; json += String((unsigned)ipCache);
        json += ",\"ipCachePeak\":"; json += String((unsigned)ipPeak);
        json += ",\"dnsBlockedRecent\":[";
        for (size_t i = 0; i < recentBlocked; ++i) {
            if (i > 0) json += ",";
            json += "{\"domain\":\""; json += wifiBridgeJsonEscape(String(entries[i].domain));
            json += "\",\"count\":"; json += String(entries[i].count);
            json += ",\"lastBlockedAt\":"; json += String(entries[i].lastBlockedAtUptimeSeconds);
            json += "}";
        }
        json += "]}";
        req->send(200, "application/json", json);
    });

    server.on("/api/wifi-bridge/set", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(401, "text/plain", "unauthorized"); return; }
        bool changed = false, wifiChanged = false;
        if (req->hasParam("upstreamEnable")) {
            gWifiBridgeCfg.enabled = req->getParam("upstreamEnable")->value().toInt() != 0;
            changed = true; wifiChanged = true;
        }
        if (req->hasParam("dnsEnable")) {
            gDnsFilterCfg.enabled = req->getParam("dnsEnable")->value().toInt() != 0;
            changed = true;
        }
        if (req->hasParam("dnsAllow")) {
            String v = req->getParam("dnsAllow")->value(); v.trim();
            if (v.length() < (int)sizeof(gDnsFilterCfg.allowlist)) {
                wifiBridgeCopyStr(gDnsFilterCfg.allowlist, sizeof(gDnsFilterCfg.allowlist), v);
                changed = true;
            }
        }
        if (req->hasParam("dnsBlock")) {
            String v = req->getParam("dnsBlock")->value(); v.trim();
            if (v.length() < (int)sizeof(gDnsFilterCfg.blocklist)) {
                wifiBridgeCopyStr(gDnsFilterCfg.blocklist, sizeof(gDnsFilterCfg.blocklist), v);
                changed = true;
            }
        }
        if (changed) wifiBridgeSaveConfig();
        if (wifiChanged) wifiBridgeRequestApply();
        req->send(200, "text/plain", "OK");
    });

    server.on("/api/wifi-bridge/add", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(401, "text/plain", "unauthorized"); return; }
        if (!req->hasParam("ssid")) { req->send(400, "text/plain", "missing ssid"); return; }
        String ssid = req->getParam("ssid")->value();
        String pass = req->hasParam("pass") ? req->getParam("pass")->value() : String();
        ssid.trim();
        if (ssid.isEmpty() || ssid.length() > 32 || pass.length() > 63) {
            req->send(400, "text/plain", "invalid length"); return;
        }
        if (wifiBridgeFindNetwork(ssid) < 0 && gWifiBridgeCfg.networkCount >= MAX_UPSTREAM_NETWORKS) {
            req->send(400, "text/plain", "limit reached"); return;
        }
        bool overwritePass = req->hasParam("pass");
        if (!wifiBridgeAddOrUpdateNetwork(ssid, pass, overwritePass, apSSID)) {
            req->send(400, "text/plain", "save failed"); return;
        }
        wifiBridgeSaveConfig();
        wifiBridgeRequestApply();
        req->send(200, "text/plain", "OK");
    });

    server.on("/api/wifi-bridge/delete", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(401, "text/plain", "unauthorized"); return; }
        if (!req->hasParam("ssid")) { req->send(400, "text/plain", "missing ssid"); return; }
        String ssid = req->getParam("ssid")->value(); ssid.trim();
        if (!wifiBridgeRemoveNetwork(ssid)) { req->send(404, "text/plain", "not found"); return; }
        wifiBridgeSaveConfig();
        wifiBridgeRequestApply();
        req->send(200, "text/plain", "OK");
    });

    server.on("/api/wifi-bridge/blocked-clear", HTTP_GET, [](AsyncWebServerRequest* req) {
        if (!checkToken(req)) { req->send(401, "text/plain", "unauthorized"); return; }
        gDnsFilter.clearBlockedRequests();
        dnsIpBlockerClear();
        req->send(200, "text/plain", "OK");
    });
#endif

    server.begin();
    DLOGLN("Web server started");
}

// ═══════════════════════════════════════════
//  CAN Task (pinned to Core 1)
// ═══════════════════════════════════════════

void canTask(void* param) {
    // Register this task with the watchdog (5 second timeout)
    esp_task_wdt_add(NULL);

    CanFrame frame;
    uint32_t normalStartMs = millis();  // boot time; clears crash counter after 10s
    bool     crashCleared  = false;    // true once crash counter has been cleared
    uint32_t logLastMs     = 0;  // last 1 Hz log check (millis)
    uint8_t  prevAccState = 0;   // tracks AP state transitions for auto-restart

    // One-shot CAN ID frequency scan — collects for 30s then logs to diag
    struct IdEntry { uint32_t id; uint32_t cnt; };
    static IdEntry idScan[256];  // static: avoids 2KB stack usage
    memset(idScan, 0, sizeof(idScan));
    uint8_t  idScanN    = 0;
    bool     idScanDone = false;

    // Diagnostic log — state tracking for transition detection
    bool     log_prevCanOK     = false;
    bool     log_prevFsdEnable = cfg.fsdEnable;
    bool     log_prevFsdTrig   = false;
    bool     log_prevHB        = false;
    uint32_t log_prevErrCount  = 0;
    uint32_t log_fsdModAt      = 0;   // modifiedCount when FSD last triggered

    for (;;) {
        // Feed watchdog — 30s TWDT (see esp_task_wdt_init below)
        esp_task_wdt_reset();

        // ── Bus-Off auto-recovery ──────────────────────────────────
        twai_status_info_t twaiStatus;
        if (twai_get_status_info(&twaiStatus) == ESP_OK) {
            if (twaiStatus.state == TWAI_STATE_BUS_OFF) {
                if (cfg.canOK) {
                    // Transition into bus-off: clear stale gesture state so
                    // spurious noise frames during recovery can't complete a
                    // partially-accumulated HB tap sequence.
                    resetStalkGestureState();
                    // Log TEC/REC counters to help diagnose who is causing errors.
                    // TEC high → ESP32 is transmitting bad frames (firmware/wiring issue on TX)
                    // REC high → ESP32 is receiving error frames (car-side or CAN-H/L wiring fault)
                    uint32_t up = (millis() - cfg.uptimeStart) / 1000;
                    char errmsg[64];
                    snprintf(errmsg, sizeof(errmsg),
                             "bus-off TEC=%u REC=%u tx_err=%u rx_err=%u",
                             (unsigned)twaiStatus.tx_error_counter,
                             (unsigned)twaiStatus.rx_error_counter,
                             (unsigned)twaiStatus.tx_failed_count,
                             (unsigned)twaiStatus.rx_missed_count);
                    addDiagLog(up, errmsg);
                }
                cfg.canOK = false;
                // Recovery handled internally by driver's read()/send()
                // via recoverWithCooldown() — no external trigger needed.
            } else if (!cfg.canOK && canDriver.isDriverOK()) {
                // Driver recovered from bus-off but no frame has arrived yet.
                // Sync canOK so the UI reflects the restored state immediately
                // rather than waiting for the first successful frame read.
                cfg.canOK = true;
            }
        }

        // ── Normal frame processing ────────────────────────────────
        bool activity = false;
        while (canDriver.read(frame)) {
            cfg.canOK = true;
            activity = true;
            cfg.rxCount++;
            handleMessage(frame, canDriver);
            updatePerfTest(telemSpeedRaw(), telemTorqueRear(), telemBrake());
            // ID scan: track unique IDs for first 30s
            if (!idScanDone) {
                bool found = false;
                for (uint8_t i = 0; i < idScanN; i++) {
                    if (idScan[i].id == frame.id) { idScan[i].cnt++; found = true; break; }
                }
                if (!found && idScanN < 255) { idScan[idScanN].id = frame.id; idScan[idScanN].cnt = 1; idScanN++; }
            }
        }

        // ── AP auto-restart on disengage ──────────────────────────────
        if (prevAccState > 0 && cfg.accState == 0 && cfg.canOK) {
            tryAPRestart(canDriver);
            if (cfg.apRestart) {
                uint32_t up = (millis() - cfg.uptimeStart) / 1000;
                addDiagLog(up, cfg.apRestartValid ? "AP disengaged -> restart injected"
                                                  : "AP disengaged -> no cache");
            }
        }
        prevAccState = cfg.accState;

        // ── Clear crash counter after 10s of normal operation ──────
        if (!crashCleared && millis() - normalStartMs >= 10000) {
            crashCleared = true;
            // Use a local Preferences object — avoids racing with the global
            // `prefs` used by saveConfig() on Core 0.
            Preferences sysPrefs;
            sysPrefs.begin("sys", false);
            sysPrefs.putInt("crashes", 0);
            sysPrefs.end();
        }

        // ── CAN ID scan: log all IDs at 30s sorted by ID number ──────
        if (!idScanDone && millis() - normalStartMs >= 30000) {
            idScanDone = true;
            // Sort by ID ascending (selection sort, small N). Guard N<2 — if zero
            // frames arrived in 30s, `idScanN - 1` underflows uint8_t → 255 and
            // would iterate over uninitialised slots.
            for (uint8_t i = 0; idScanN >= 2 && i < idScanN - 1; i++)
                for (uint8_t j = i + 1; j < idScanN; j++)
                    if (idScan[j].id < idScan[i].id) {
                        IdEntry t = idScan[i]; idScan[i] = idScan[j]; idScan[j] = t;
                    }
            uint32_t up = (millis() - cfg.uptimeStart) / 1000;
            char hdr[40];
            snprintf(hdr, sizeof(hdr), "=== CAN IDs (%u unique, 30s) ===", idScanN);
            addDiagLog(up, hdr);
            char buf[80];
            for (uint8_t i = 0; i < idScanN; i += 6) {
                int p = 0;
                for (uint8_t j = i; j < i + 6 && j < idScanN; j++)
                    p += snprintf(buf + p, sizeof(buf) - p, "%03X:%u ", idScan[j].id, idScan[j].cnt);
                addDiagLog(up, buf);
            }
        }

        // ── Diagnostic log — 1 Hz event transition check ──────────
        uint32_t nowMs = millis();
        if (nowMs - logLastMs >= 1000) {
            logLastMs = nowMs;
            uint32_t up = (nowMs - cfg.uptimeStart) / 1000;
            char msg[64];

            if (cfg.canOK != log_prevCanOK) {
                addDiagLog(up, cfg.canOK ? "CAN OK" : "CAN ERROR");
                log_prevCanOK = cfg.canOK;
            }
            if (cfg.fsdEnable != log_prevFsdEnable) {
                addDiagLog(up, cfg.fsdEnable ? "FSD enable=ON" : "FSD enable=OFF");
                log_prevFsdEnable = cfg.fsdEnable;
            }
            if (cfg.fsdTriggered != log_prevFsdTrig) {
                if (cfg.fsdTriggered) {
                    addDiagLog(up, "FSD triggered");
                    log_fsdModAt = cfg.modifiedCount;
                } else {
                    snprintf(msg, sizeof(msg), "FSD released (injected %u)",
                             (unsigned)(cfg.modifiedCount - log_fsdModAt));
                    addDiagLog(up, msg);
                }
                log_prevFsdTrig = cfg.fsdTriggered;
            }
            if (cfg.highBeamForce != log_prevHB) {
                if (cfg.highBeamForce) {
                    snprintf(msg, sizeof(msg), "HB force ON adaptive=%s",
                             cfg.adaptiveLighting ? "Y" : "N");
                    addDiagLog(up, msg);
                } else {
                    addDiagLog(up, "HB force OFF");
                }
                log_prevHB = cfg.highBeamForce;
            }
            if (cfg.errorCount > log_prevErrCount) {
                snprintf(msg, sizeof(msg), "errors +%u total=%u",
                         (unsigned)(cfg.errorCount - log_prevErrCount),
                         (unsigned)cfg.errorCount);
                addDiagLog(up, msg);
                log_prevErrCount = cfg.errorCount;
            }
        }

        // LED: on during activity, off when idle
        digitalWrite(PIN_LED, activity ? HIGH : LOW);
        vTaskDelay(1);
    }
}

// ═══════════════════════════════════════════
//  Arduino setup / loop
// ═══════════════════════════════════════════

void setup() {
    Serial.begin(115200);
    delay(1000);
    DLOGLN("\n=== Tesla Controller ===");

    // LED
    pinMode(PIN_LED, OUTPUT);
    digitalWrite(PIN_LED, LOW);

    // ── Crash counter / safe mode ──────────────────────────────────
    // If the device crashes 3+ times in a row within 10s, enter safe mode
    // (WiFi only, no CAN) so the user can re-flash firmware.
    {
        Preferences sysPrefs;
        sysPrefs.begin("sys", false);
        int crashes = sysPrefs.getInt("crashes", 0) + 1;
        if (crashes >= 3) {
            safeModeActive = true;
            // Reset counter now so next boot (after reflash) can escape safe mode.
            // canTask does not run in safe mode, so the counter would never be
            // cleared by the normal 10 s path — device would be permanently stuck.
            sysPrefs.putInt("crashes", 0);
        } else {
            sysPrefs.putInt("crashes", crashes);
        }
        sysPrefs.end();
        DLOG(safeModeActive ? "[SAFE MODE] crash count=%d, counter reset, CAN disabled\n"
                            : "[Boot] crash count=%d\n", crashes);
    }

    // ── Watchdog: 30-second timeout ────────────────────────────────
    // Earlier 5 s was too aggressive: legitimate slow operations in the
    // main loop (WiFi.begin() during AP+STA channel switch, SPIFFS flush
    // under flash contention, mbedTLS handshake blocking the Wi-Fi stack
    // during OTA check) routinely exceed 5 s and cause rst:0xc
    // (RTC_SW_CPU_RST) panics on the Waveshare Wi-Fi bridge in the field.
    // 30 s still catches real infinite loops / deadlocks without killing
    // the device during normal connectivity hiccups.
    esp_task_wdt_init(30, true);  // 30s timeout, panic on trigger

    // Migrate NVS keys from verbose names to obfuscated names (one-time, on update)
    migrateNvsKeys();

    // Load saved config from NVS
    loadConfig();
    DLOG("Config loaded: HW=%d, Profile=%d\n", cfg.hwMode, cfg.speedProfile);

    cfg.uptimeStart = millis();

    // Init SPIFFS — must come before boot log entry so the marker lands in the file
    setupSpiffs(FIRMWARE_VERSION);

    // Boot log entry
    {
        char bootMsg[64];
        snprintf(bootMsg, sizeof(bootMsg), "BOOT v" FIRMWARE_VERSION " HW%u fsd=%s b=" __TIME__,
                 (unsigned)cfg.hwMode,
                 cfg.fsdEnable ? "ON" : "OFF");
        addDiagLog(0, bootMsg);
    }

    // Reset reason — helps diagnose field crashes without a serial cable.
    // Values from esp_reset_reason_t: POWERON=1, SW=3, PANIC=4, INT_WDT=5,
    // TASK_WDT=6, WDT=7, DEEPSLEEP=8, BROWNOUT=9, SDIO=10.
    {
        const char* why;
        switch (esp_reset_reason()) {
            case ESP_RST_POWERON:   why = "power-on";    break;
            case ESP_RST_SW:        why = "sw restart";  break;
            case ESP_RST_PANIC:     why = "PANIC";       break;
            case ESP_RST_INT_WDT:   why = "INT_WDT";     break;
            case ESP_RST_TASK_WDT:  why = "TASK_WDT";    break;
            case ESP_RST_WDT:       why = "WDT other";   break;
            case ESP_RST_BROWNOUT:  why = "BROWNOUT";    break;
            case ESP_RST_DEEPSLEEP: why = "deepsleep";   break;
            default:                why = "unknown";     break;
        }
        char msg[48];
        snprintf(msg, sizeof(msg), "reset: %s", why);
        addDiagLog(0, msg);

        // Retrieve last-restart reason persisted to NVS (survives any reboot
        // — sw/panic/wdt/brownout). Cleared after reading so next boot is clean.
        Preferences diag;
        if (diag.begin("diag", false)) {
            String last = diag.getString("rr", "");
            char rrMsg[80];
            snprintf(rrMsg, sizeof(rrMsg), "prev: %s",
                     last.length() ? last.c_str() : "(none)");
            addDiagLog(0, rrMsg);
            if (last.length()) diag.remove("rr");
            diag.end();
        } else {
            addDiagLog(0, "prev: (nvs open failed)");
        }
    }

    // Init CAN (skip in safe mode)
    if (!safeModeActive) {
        if (canDriver.init()) {
            cfg.canOK = true;
            DLOGLN("ESP32 TWAI ready @ 500k");
        } else {
            cfg.canOK = false;
            DLOGLN("CAN init failed!");
        }

    } else {
        cfg.canOK = false;
    }

    // Always use AP+STA mode so WiFi scanning is available even without a router configured.
    // Upstream-proven WiFi config for Tesla browser compatibility:
    //   persistent(false)     — skip NVS writes on every WiFi setting (reduces flash wear, avoids races)
    //   setAutoReconnect(true)— STA auto-reconnects on router drop
    //   AP IP 9.9.9.9         — avoids all common phone-hotspot subnets (172.20.10.x, 192.168.43.x, 192.168.4.x)
    // Note: setSleep(false) and channel-6 lock removed — in APSTA the AP must follow STA's channel,
    // and setSleep(false) increased thermal/power load which correlated with client DHCP reassignment loops.
    WiFi.persistent(false);
    WiFi.setAutoReconnect(true);
    WiFi.mode(WIFI_AP_STA);

    // Connect to router first (if configured) so we can read the assigned STA IP
    if (staSSID[0] != '\0') {
        // Bring up AP on 9.9.9.9 while STA connects (AP channel auto-follows STA in APSTA mode)
        WiFi.softAPdisconnect(false);
        delay(100);
        WiFi.softAPConfig(IPAddress(9,9,9,9), IPAddress(9,9,9,9), IPAddress(255,255,255,0));
        WiFi.softAP(apSSID, apPass[0] ? apPass : nullptr);
        WiFi.begin(staSSID, staPass[0] ? staPass : nullptr);
        DLOG("WiFi STA: connecting to '%s'...\n", staSSID);
        uint32_t t0 = millis();
        while (WiFi.status() != WL_CONNECTED && millis() - t0 < 10000) {
            delay(200);
        }
        staConnected = (WiFi.status() == WL_CONNECTED);
        if (staConnected) {
            char logMsg[64];
            snprintf(logMsg, sizeof(logMsg), "STA connected %s  AP: 9.9.9.9",
                     WiFi.localIP().toString().c_str());
            DLOGLN(logMsg);
            addDiagLog(0, logMsg);
        } else {
            DLOGLN("WiFi STA connect failed");
            addDiagLog(0, "STA connect FAILED");
        }
    } else {
        // No router configured — AP only on 9.9.9.9
        WiFi.softAPdisconnect(false);
        delay(100);
        WiFi.softAPConfig(IPAddress(9,9,9,9), IPAddress(9,9,9,9), IPAddress(255,255,255,0));
        WiFi.softAP(apSSID, apPass[0] ? apPass : nullptr);
    }
#ifdef WIFI_BRIDGE_ENABLED
    // WiFi bridge mode: replace captive-portal DNS with filtering DNS on :53.
    // Captive portal is unneeded because AP clients hit http://<apIP>/ directly,
    // and port 53 is owned by the bridge's DNS filter+forwarder.
    //
    // Force AP's DHCP server to hand out the AP IP as DNS — arduino-esp32's
    // default behaviour can leave DNS unset, so phones fall back to cached/mobile
    // DNS and bypass the filter entirely.
    {
        esp_netif_t* apNetif = esp_netif_get_handle_from_ifkey("WIFI_AP_DEF");
        if (apNetif) {
            esp_netif_dhcps_stop(apNetif);
            esp_netif_dns_info_t dnsInfo = {};
            dnsInfo.ip.type = ESP_IPADDR_TYPE_V4;
            dnsInfo.ip.u_addr.ip4.addr = static_cast<uint32_t>(WiFi.softAPIP());
            esp_netif_set_dns_info(apNetif, ESP_NETIF_DNS_MAIN, &dnsInfo);
            dhcps_offer_t offerDns = OFFER_DNS;
            esp_netif_dhcps_option(apNetif, ESP_NETIF_OP_SET,
                ESP_NETIF_DOMAIN_NAME_SERVER, &offerDns, sizeof(offerDns));
            esp_netif_dhcps_start(apNetif);
        }
    }
    wifiBridgeLoadConfig();
    gDnsFilter.begin(53);
    wifiBridgeRequestApply();
    xTaskCreatePinnedToCore(
        [](void*) {
            for (;;) {
                gDnsFilter.processNextRequest(gDnsFilterCfg, WiFi.status() == WL_CONNECTED);
                vTaskDelay(pdMS_TO_TICKS(10));
            }
        },
        "DNSFilter", 4096, NULL, 1, NULL, 0);
    DLOG("WiFi bridge: DNS filter on :53, AP=%s IP=%s\n", apSSID, WiFi.softAPIP().toString().c_str());
#else
    // Captive portal DNS — redirect all domains to ESP32 AP IP.
    // Causes iOS/Android to detect a captive portal and pop up the browser automatically.
    dnsServer.setErrorReplyCode(DNSReplyCode::NoError);
    dnsServer.start(53, "*", WiFi.softAPIP());
    DLOG("WiFi AP: %s  IP: %s\n", apSSID, WiFi.softAPIP().toString().c_str());
#endif

    // Start web server
    setupWebServer();

    // mDNS — accessible via fsd.local on both AP and LAN
    if (MDNS.begin("fsd")) {
        MDNS.addService("http", "tcp", 80);
        DLOGLN("mDNS: fsd.local");
        addDiagLog(0, "mDNS: fsd.local");
    } else {
        DLOGLN("mDNS: start failed");
        addDiagLog(0, "mDNS start FAILED");
    }

    // Pin CAN processing to Core 1 — skip in safe mode
    if (!safeModeActive) {
        xTaskCreatePinnedToCore(canTask, "CAN", 8192, NULL, 2, NULL, 1);
    }

    // Register the Arduino loop task with TWDT so hangs in AsyncTCP/DNS/OTA
    // are caught instead of silently blocking forever.
    esp_task_wdt_add(NULL);
}

void loop() {
    esp_task_wdt_reset();

    // Handle OTA restart safely outside async context
    if (otaPendingRestart) {
        delay(1000);  // let response finish sending
        flushLogsToSpiffs();  // persist the "restart: …" diag line before reboot
        ESP.restart();
    }

#ifdef WIFI_BRIDGE_ENABLED
    // WiFi bridge: thermal + upstream reconnect + blocklist IP cache + NAT sync.
    // DNS filtering itself runs in its own pinned task (set up in setup()).
    //
    // Skip non-essential Wi-Fi service during OTA. serviceUpstreamWiFi() can
    // call WiFi.begin() which blocks for seconds, and with the OTA task on
    // core 0 holding the Wi-Fi stack for a TLS handshake with the full
    // cert bundle, that stall easily exceeds the 5 s TWDT panic timeout and
    // triggers rst:0xc (RTC_SW_CPU_RST). Observed on v1.4.19 when a user
    // clicked "检查更新".
    if (!otaIsActive()) {
        serviceThermalStatus();
        serviceUpstreamWiFi(apSSID);
        dnsIpPolicyService(
            gDnsFilterCfg.allowlist,
            gDnsFilterCfg.blocklist,
            gDnsFilterCfg.enabled ? 1 : 0,
            WiFi.status() == WL_CONNECTED ? 1 : 0
        );
        syncNATState();
    }
#else
    // Captive portal — must be called frequently to answer DNS queries promptly
    dnsServer.processNextRequest();
#endif

    // Flush new RAM log entries to SPIFFS every 3 s (Core 0 only).
    static uint32_t lastFlushMs = 0;
    uint32_t nowMs = millis();
    if (nowMs - lastFlushMs >= 3000) {
        lastFlushMs = nowMs;
        flushLogsToSpiffs();
    }

    // Crash-counter reset from loop: canTask may stall or be disabled (safe mode
    // off-path). If we reach 60s of uptime on Core 0 without crashing, clear the
    // counter ourselves so isolated crashes days apart don't latch safeMode.
    static bool loopCrashCleared = false;
    if (!loopCrashCleared && nowMs - cfg.uptimeStart >= 60000) {
        loopCrashCleared = true;
        Preferences sysPrefs;
        sysPrefs.begin("sys", false);
        if (sysPrefs.getInt("crashes", 0) != 0) sysPrefs.putInt("crashes", 0);
        sysPrefs.end();
    }

    // Heap guard: AsyncWebServer heap fragmentation causes silent request
    // failures after long uptime. Auto-restart when free heap < 20 KB.
    static uint32_t lastHeapMs  = 0;
    static bool     heapWarnSent = false;
    if (nowMs - lastHeapMs >= 5000) {
        lastHeapMs = nowMs;
        uint32_t freeHeap = ESP.getFreeHeap();
        if (freeHeap < 20000 && !heapWarnSent) {
            uint32_t up = (nowMs - cfg.uptimeStart) / 1000;
            char msg[48];
            snprintf(msg, sizeof(msg), "low heap %u B", (unsigned)freeHeap);
            addDiagLog(up, msg);
            heapWarnSent = true;
        } else if (freeHeap >= 20000) {
            heapWarnSent = false;  // reset so it can warn again if heap drops again
        }
    }

    vTaskDelay(10);
}
